language: r
env:
    global:
        - _R_CHECK_TIMINGS_=0
branches:
    only:
        - master
        - ci_nojava
        - task_ops
warnings_are_errors: true
apt_packages:
    - r-cran-rjava
    - libgmp-dev
r_github_packages:
    - berndbischl/BBmisc
    - berndbischl/parallelMap
    - berndbischl/ParamHelpers
    - jimhester/covr
r_binary_packages:
    - ada
    - adabag
    # - bartMachine
    - brnn
    - bst
    - care
    - caret
    - checkmate
    - class
    - clue
    - cluster
    - clusterSim
    - clValid
    - cmaes
    - CoxBoost
    - crs
    - Cubist
    - DiceKriging
    - DiceOptim
    - DiscriMiner
    - deepnet
    - e1071
    - earth
    - elasticnet
    - elmNN
    - emoa
    # - extraTrees
    - fields
    - flare
    - FNN
    - frbs
    - FSelector
    - gbm
    - GenSA
    - ggplot2
    - ggvis
    - glmnet
    - Hmisc
    - irace
    - kernlab
    - kknn
    - klaR
    - knitr
    - kohonen
    - laGP
    - LiblineaR
    - lqa
    - MASS
    - mboost
    - mco
    - mda
    - mlbench
    - modeltools
    - mRMRe
    - neuralnet
    - nnet
    - nodeHarvest
    - pamr
    - party
    - penalized
    - pls
    - plyr
    # - PMCMR
    - pROC
    - randomForest
    - randomForestSRC
    - reshape2
    - RCurl
    - RSNNS
    - rFerns
    - rjson
    - rmarkdown
    - robustbase
    - ROCR
    - rpart
    - rrlda
    - rsm
    - RWeka
    - sda
    - shiny
    - sparsediscrim
    - sparseLDA
    - stepPlr
    - stringi
    - SwarmSVM
    - testthat
    - tgp
    - TH.data
    - XML
before_script:
    - curl -L https://raw.githubusercontent.com/mllg/travis-r-tools/master/update-packages.r -o /tmp/update-packages.r
    - Rscript /tmp/update-packages.r
    - sudo R CMD javareconf
    - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip

after_success:
    - Rscript -e 'covr::codecov()'
notifications:
  email:
    recipients:
        - xihuil.silence@gmail.com
    on_success: change
    on_failure: always
